# Generated by Django 4.0.6 on 2022-07-11 11:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_accounttiers_arbitrary_thumbnail_sizes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Images',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='account_tiers',
            new_name='account_tier',
        ),
        migrations.AddField(
            model_name='imagelinks',
            name='expiring_time',
            field=models.SmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='imagelinks',
            name='expiring',
            field=models.BooleanField(default=False),
        ),
    ]
