# Generated by Django 4.0.6 on 2022-07-11 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_imagelinks_link_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagelinks',
            name='link_name',
            field=models.CharField(default='<django.db.models.query_utils.DeferredAttribute object at 0x000002A569D42730> - <django.db.models.fields.SmallIntegerField>', max_length=100),
        ),
    ]
