# Generated by Django 4.0.6 on 2022-07-11 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_imagelinks_link_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagelinks',
            name='link_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='main/templates/static/'),
        ),
    ]
