# Generated by Django 4.0.6 on 2022-07-11 18:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_imagelinks_link_name_alter_images_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='expiring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='images',
            name='expiring_time',
            field=models.SmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='images',
            name='height',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='images',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='images',
            name='original',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='images',
            name='original_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='images',
            name='width',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(height_field='height', upload_to='main/templates/static/image', width_field='width'),
        ),
        migrations.DeleteModel(
            name='ImageLinks',
        ),
    ]
