# Generated by Django 4.0.6 on 2022-07-11 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_images_expiring_images_expiring_time_images_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(height_field='height', upload_to='main/templates/image', width_field='width'),
        ),
    ]
