# Generated by Django 4.0.6 on 2022-07-12 17:39

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_images_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(height_field='height', upload_to=pathlib.PureWindowsPath('E:/PyCharm 2020.2.4/image_upload/image_upload/staticfiles'), width_field='width'),
        ),
    ]
