# Generated by Django 4.0.6 on 2022-07-12 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_images_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='expiring',
        ),
    ]
