# Generated by Django 4.0.6 on 2022-07-12 23:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_images_expiring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='expiring_time',
            field=models.SmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(30000), django.core.validators.MinValueValidator(300)]),
        ),
    ]
